# Generated by Django 4.1.7 on 2023-09-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100, unique=True)),
                ('filiere', models.CharField(blank=True, max_length=100, unique=True)),
                ('promotion', models.CharField(choices=[('preparatoire', 'Preparatoire'), ('bac_1', 'Bac 1'), ('bac_2', 'Bac 2'), ('bac_3', 'Bac 3'), ('master_1', 'Master 1'), ('master_2', 'Master 2')], default='preparatoire', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.PositiveIntegerField(default=1)),
                ('nom_salle', models.CharField(blank=True, max_length=50)),
                ('promotion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=50)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('cours', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire.departement')),
                ('salles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire.salles')),
            ],
        ),
    ]
